carthorse:
  version-from: setup.py
  when:
    - version-not-tagged
  actions:
    - run: "pip install -e .[build]"
    - run: "python setup.py sdist bdist_wheel"
    - run: "twine upload -u chrisw -p $PYPI_PASS dist/*"
    - create-tag
