language: python

# for container-y googdness:
sudo: false

python:
  - "2.7"

install:
  - "pip install -Ue .[test,build]"

# command to run tests, e.g. python setup.py test
script: coverage run --source configurator -m nose

after_success:
  - coveralls

deploy:
  provider: pypi
  user: chrisw
  password:
    secure: x
  on:
    tags: true
    repo: Simplistix/configurator
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
